### ISSUE TITLE
signInWithPhoneNumber returns Invalid format

### ISSUE THREAD

**Issue by ahmadyousefdev** [thareekanvar/react-native-firebase-phone-auth#11]
Hi,
Thanks for the code, you're the only one who solved the firebase phone auth problem in expo until now!

I tried implementing your code in my app and I can see that it retrieves the `token` successfully. But I can see the error is with this code
```
 const captchaVerifier = {
            type: 'recaptcha',
            verify: () => Promise.resolve(token)
        }
```
the code above in my case only returns `{"type":"recaptcha"}` which makes this function `firebase.auth().signInWithPhoneNumber(phone, captchaVerifier)` not work and return `Invalid format` . Any advice in this matter ?

**Comment by thareekanvar** [comment]
updating for new sdk soon will release ...

**Comment by premnathdey** [comment]
Hi, 
When I am clicking on "Continue to the app" it doesn't navigate me to SIGN IN page neither I get OTP on my device.

**Comment by thareekanvar** [comment]
check my other branch other than master ... i m on it

**Comment by thareekanvar** [comment]
> Hi,
> When I am clicking on "Continue to the app" it doesn't navigate me to SIGN IN page neither I get OTP on my device.

Bro this is Outdated that why u get problem .. i am updating with new SDK ... u can check my other branch ..soon as possible i will fix

**Comment by premnathdey** [comment]
How can I update captcha URL

**Comment by thareekanvar** [comment]
> How can I update captcha URL

You can host in ur firebase ..check firebase hosting ... and all problem solved with new updates
