### ISSUE TITLE
Recapture verification failed: DUPF

### ISSUE THREAD

**Issue by shoaibhasan-crowdbotics** [thareekanvar/react-native-firebase-phone-auth#13]
Hi, I sign up with phone number and I sign out.
And I tried to sign up again.
I got "Recapture verification failed: DUPF". Error code is "auth/captcha-check-failed"
Can you help this?
Thanks
![image](https://user-images.githubusercontent.com/61243739/75841353-c201f680-5d8a-11ea-9df9-7c44de6d2bc4.png)

**Comment by shoaibhasan-crowdbotics** [comment]
May web browser have some old session?

**Comment by thareekanvar** [comment]
> May web browser have some old session?

what is the updates u do in that codes ... can i see ur code ?

**Comment by thareekanvar** [comment]
> Hi, I sign up with phone number and I sign out.
> And I tried to sign up again.
> I got "Recapture verification failed: DUPF". Error code is "auth/captcha-check-failed"
> Can you help this?
> Thanks
> ![image](https://user-images.githubusercontent.com/61243739/75841353-c201f680-5d8a-11ea-9df9-7c44de6d2bc4.png)

can u just try in any other mobile phone ...??

**Comment by shoaibhasan-crowdbotics** [comment]
I cloned your code to my project. And I tried at your project too. but same issue.
I tried at other phones too. you can check at your code.

**Comment by shoaibhasan-crowdbotics** [comment]
![image](https://user-images.githubusercontent.com/61243739/75864214-e677c600-5dbe-11ea-8751-e23b05d517cb.png)
![image](https://user-images.githubusercontent.com/61243739/75864266-fc858680-5dbe-11ea-8724-1af55a5ed049.png)

**Comment by shoaibhasan-crowdbotics** [comment]
what is your skp?

**Comment by shoaibhasan-crowdbotics** [comment]
can you help me?

**Comment by thareekanvar** [comment]
> can you help me?

can i see which URL using " https://workers-ef768.firebaseapp.com/captcha.html "

**Comment by shoaibhasan-crowdbotics** [comment]
I tested your git hub source code. it have same problem. can you check your code?

**Comment by thareekanvar** [comment]
> I tested your git hub source code. it have same problem. can you check your code?

me also checked no problem .... " can i see which URL using "

**Comment by thareekanvar** [comment]
> auth/captcha-check-failed

auth/captcha-check-failed
Thrown if the reCAPTCHA response token was invalid, expired, or if this method was called from a non-whitelisted domain.

refer : https://firebase.google.com/docs/reference/js/firebase.auth.PhoneAuthProvider

**Comment by shoaibhasan-crowdbotics** [comment]
Thank you. yes I referenced. But Do you think why can the issue cause?

**Comment by thareekanvar** [comment]
> Thank you. yes I referenced. But Do you think why can the issue cause?

i think , u need to whitelist ur domain

**Comment by shoaibhasan-crowdbotics** [comment]
![image](https://user-images.githubusercontent.com/61243739/76004699-e1dd1a00-5f44-11ea-9e06-cbe08449ea34.png)
I used default domain at firebase.

**Comment by shoaibhasan-crowdbotics** [comment]
what is your skype id?

**Comment by thareekanvar** [comment]
> what is your skype id?

i dont have skype bro

**Comment by thareekanvar** [comment]
> ![image](https://user-images.githubusercontent.com/61243739/76004699-e1dd1a00-5f44-11ea-9e06-cbe08449ea34.png)
> I used default domain at firebase.

so the token may be invalid ... check the token which u get...

**Comment by shoaibhasan-crowdbotics** [comment]
I have to make other domain at firebase?

**Comment by shoaibhasan-crowdbotics** [comment]
Hi, Can you help me to setup custom domain at firebase?
Ofc, I will help you.

**Comment by shoaibhasan-crowdbotics** [comment]
Hi, I am getting the following error when sign in with phone number by firebase.
sign in with phone number
sign out
sign in again, got error.
If I delete the app and reinstall, I can sign in again.

Error code => "auth/captcha-check-failed"
Error message => "Recaptcha verification failed - DUPE"

Thanks

**Comment by thareekanvar** [comment]
> Hi, Can you help me to setup custom domain at firebase?
> Ofc, I will help you.

custom domain u can easily add in firebase bro .... just search google

**Comment by thareekanvar** [comment]
> Hi, I am getting the following error when sign in with phone number by firebase.
> sign in with phone number
> sign out
> sign in again, got error.
> If I delete the app and reinstall, I can sign in again.
> 
> Error code => "auth/captcha-check-failed"
> Error message => "Recaptcha verification failed - DUPE"
> 
> Thanks

okey bro i will check it out ...

**Comment by shoaibhasan-crowdbotics** [comment]
Hi, Did you check and fix issue? Thanks

**Comment by thareekanvar** [comment]
> Hi, Did you check and fix issue? Thanks

Made a new starter kit for phone auth users :+1: 

https://github.com/thareekanvar/expo-firebase-phonenumber-auth-starter
