### ISSUE TITLE
Unable to load authenticate user

### ISSUE THREAD

**Issue by vivekrj0** [thareekanvar/react-native-firebase-phone-auth#14]
When the SentOtp button is clicked, it goes to the captcha URL, and the page loads every time when the captcha verified.
My hosting URL: https://p2p-energy-5cfad.web.app

**Comment by thareekanvar** [comment]
@vivekrj0  dont wory bro i made a new starter with latest SDK and Fully updated ..

Refer this link : https://github.com/thareekanvar/expo-firebase-phonenumber-auth-starter

this is now not updated .. so u can refer my new one bro ..its simple

**Comment by thareekanvar** [comment]
@vivekrj0 sry for the late reply i had some health issues ..

**Comment by vivekrj0** [comment]
@thareekanvar Thanks for the help.

**Comment by thareekanvar** [comment]
@vivekrj0 happy to help others.. knowledge will increase :)
