### ISSUE TITLE
How to depoly the Captcha.html in the firebase??

### ISSUE THREAD

**Issue by mahendra350** [thareekanvar/react-native-firebase-phone-auth#15]
Please help me how the  captcha.html  to deploy in the firebase.

**Comment by thareekanvar** [comment]
https://github.com/thareekanvar/expo-firebase-phonenumber-auth-starter  check this new one ...

> Please help me how the captcha.html to deploy in the firebase.

**Comment by mahendra350** [comment]
I am not using Expo CLI, In the expo, we can that expo Recaptcha , But I want this in the react-native CLI project , for that I want the process how you hosted the Captcha.html in the firebase, I tried hosting the server but index.html only I can see in the hosted server URL, not the captcha.html
