### ISSUE TITLE
Not Working in Android 

### ISSUE THREAD

**Issue by Nikesh5888** [thareekanvar/react-native-firebase-phone-auth#6]
hai the web browser in not redirecting to the code page after the capture verification in android SDK:34.0.0

**Comment by thareekanvar** [comment]
updating soon ....for SDK:35

**Comment by thareekanvar** [comment]
> hai the web browser in not redirecting to the code page after the capture verification in android SDK:34.0.0

everything updated to sdk 36 ..working fine
